services:
  - type: web
    name: loan-processing
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        fromService:
          type: web
          name: loan-processing
          envVarKey: RENDER_EXTERNAL_PORT
    plan: free 