services:
  - type: web
    name: loan-processing
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        fromService:
          type: web
          name: loan-processing
          envVarKey: RENDER_EXTERNAL_PORT
      - key: WRITER_FRAMEWORK_ENV
        value: production
      - key: APP_NAME
        value: Loan Processing App
      - key: ENV
        value: production
    plan: free 